### ISSUE TITLE
suggested change + correction

### ISSUE THREAD

**Issue by shantenujha** [ATLAS-Titan/PanDA-WMS-paper#5] opened 2017-03-12 14:07 UTC
Titan’s backfill functionality offers the opportunity not to use the pilot abstraction while still avoiding queue time over- heads. Backfill availability is the number of work nodes that cannot be used by any of the jobs already queued on Titan: All queued jobs are either too large or their walltime is too long. At any point in time, Titan’s Moab scheduler can be queried for backfill availability and a job submitted shortly after placing this query and requesting for no more than the backfill availability, is usually scheduled immediately spending almost no time in the queue.

work nodes --> worker nodes?

Propose first sentence be:

Titan’s backfill functionality offers the opportunity to avoid the overhead of queue wait times 
without using pilot abstraction. 

Propose the last sentence be:

At any point in time, Titan’s Moab scheduler can be queried for backfill availability. Based upon the result of this query, a job can be shaped to request no more than the backfill availability, and when submitted as such is usually scheduled immediately spending almost no time in the queue.

Please mention if it is a special purpose arrangement, or can anyone who queries the backfill submit to the backfill queue?

**Comment by mturilli** [comment] 2017-03-12 14:32
I did not find explicit documentation on Titan but I am under the impression anyone can interrogate Moab for backfill availability. From Moab documentation:

"Backfill operates based on this earliest job start information. Because Moab knows the earliest the highest priority job can start, and which resources it will need at that time, it can also determine which jobs can be started without delaying this job. Enabling backfill allows the scheduler to start other, lower-priority jobs so long as they do not delay the highest priority job. If backfill is enabled, Moab, protects the highest priority job's start time by creating a job reservation to reserve the needed resources at the appropriate time. Moab then can start any job that will not interfere with this reservation." (http://docs.adaptivecomputing.com/mwm/archive/6-0/8.2backfill.php)

**Comment by shantenujha** [comment] 2017-03-12 14:35
Interrogate being general, I can understand. Submit however might require special permission. thoughts?

**Comment by mturilli** [comment] 2017-03-12 14:44
I am under the impression that submission is to the normal queue and without specific flags. It just happens to be of a size and duration that matches backfill availability. Just my impression though so I will ask for confirmation to Sergey/Jack before closing the ticket.

**Comment by mturilli** [comment] 2017-04-02 20:23
Confirmed.

**Closed as completed by mturilli** 2017-04-02 20:23 UTC
